### ISSUE TITLE
Problems with big numbers

### ISSUE THREAD

**Issue by marie-bnl** [axiros/pycond#2]
I did a few tests and this module definetely struggles with big numbers.

```python
import pycond as pc

cond = pc.pycond("1006889077401993236 eq 1006889077401993236", autoconv=False)
res = cond()

print(cond, res)
```

`res` is `False` while it should be `True` here, even with autoconv disabled

**Comment by axgkl** [comment]
Confirmed and fixed, thanks.

works now:

```python

    def test_autoconv_huge(s):
        S['foo'] = 100688907740199323
        eq(s, pycond('foo eq 100688907740199323')(), True)

````

The error happened in the conversion from string format, where casting to float was tried before int, and it "successfully" created a float in scientific format. 

This did work before 

```
pycond.parse_cond(['foo', 'eq', 100688907740199323])[0](state={'foo': 100688907740199323})
```
